# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testdockerakshay

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerakshay.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_554bd51aa4234ed7a2113e38c6f36f04 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b68920a3183415bb1945dcbddb84fd8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerakshay.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_554bd51aa4234ed7a2113e38c6f36f04 }}/testdockerakshay/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdockerakshay'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3eb19ec524cf4e1983ed97fa3cc9277c }}
        images: 'testdockerakshay.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_554bd51aa4234ed7a2113e38c6f36f04 }}/testdockerakshay/studentperformance:${{ github.sha }}'